# Generated by Django 2.0.5 on 2018-04-19 16:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='img%Y/%m/%d')),
                ('des', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='描述')),
            ],
        ),
    ]
